services:
  # Backend service
  - type: web
    name: kinikaase-backend
    env: python
    plan: free
    pythonVersion: 3.12
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r api/requirements-python312.txt && cd api && python manage.py collectstatic --noinput --settings=core.production_settings && python manage.py migrate --settings=core.production_settings
    startCommand: cd api && gunicorn core.wsgi_production:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kinikaase-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: kinikaase-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://kinikaase-backend.onrender.com,https://your-frontend-domain.com
      - key: MEDIA_URL
        value: /media/
      - key: STATIC_URL
        value: /static/
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /opt/render/project/src/api/core/service-account.json
      - key: REDIS_URL
        value: redis://localhost:6379

databases:
  # PostgreSQL database
  - name: kinikaase-db
    plan: free
    databaseName: kinikaase_production
    user: kinikaase_user
