services:
  # Web service
  - type: web
    name: django-app
    runtime: python
    buildCommand: "cd api && ./build.sh"
    startCommand: "cd api && ./render-setup.sh && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: django-redis
          property: connectionString

  # Worker service for Channels
  - type: worker
    name: django-worker
    runtime: python
    buildCommand: "cd api && ./build.sh"
    startCommand: "cd api && python manage.py runworker channel_layer"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: django-redis
          property: connectionString

  # Redis service for channels
  - type: redis
    name: django-redis
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: Everywhere

# Database service
databases:
  - name: django-db
    plan: starter
    databaseName: django_app_db 