# Generated by Django 5.1.4 on 2025-01-27 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_Bg_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='background_thumbnails/'),
        ),
    ]
