# Generated by Django 5.1.4 on 2025-02-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
    ]
