# Generated by Django 5.1.4 on 2025-02-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_disappearing_message_incognito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(max_length=50),
        ),
    ]
