# Generated by Django 5.1.4 on 2025-02-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_message_media_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together={('user', 'blocked_user')},
        ),
        migrations.AlterUniqueTogether(
            name='reporteduser',
            unique_together={('user', 'reported_user')},
        ),
    ]
