# Generated by Django 5.1.4 on 2025-02-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
