# Generated by Django 5.1.4 on 2025-02-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_blockeduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedUser',
            new_name='BlockedUsers',
        ),
    ]
