# Generated by Django 5.1.4 on 2025-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_user_thumbnail_alter_reaction_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedUsers',
            new_name='BlockedUser',
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
    ]
