# Generated by Django 5.1.4 on 2025-02-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_remove_user_fcm_token_userfcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserFCMToken',
        ),
    ]
