# Generated by Django 5.1.4 on 2025-02-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_user_fcm_token_delete_userfcmtoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('message', 'user', 'emoji')},
        ),
    ]
