# Generated by Django 5.1.4 on 2025-02-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_reaction_unique_together_callsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='call_session',
        ),
        migrations.DeleteModel(
            name='CallSession',
        ),
    ]
